### ISSUE TITLE
Avoid macro whenever possible

### ISSUE THREAD

**Issue by frol** [near/units-rs#3]
I feel that macro are completely unnecessary for this task. Rust has an established idiomatic way of [`parse` + `from_str`](https://doc.rust-lang.org/stable/std/primitive.str.html#method.parse) for parsing values and [`Display` trait + `to_string`](https://doc.rust-lang.org/stable/std/fmt/trait.Display.html) for human formatted values

**Comment by willemneal** [comment]
But the macro does not have a runtime cost of parsing the string literal.  This was a rough draft and I agree that the abstractions need improvement, but the macro is definitely useful for literals.

I do wish that macros could be bound to a type.

**Comment by frol** [comment]
I feel that this whole crate could be simpler if we don't operate on string literals, but instead use dedicated methods:

```
const my_balance_1NEAR: NearBalance = NearBalance::from_near(1); // 1 NEAR
const my_balance_sub_1NEAR: NearBalance = NearBalance::from_millinear(100); // 0.1 NEAR
const my_balance_1yoctoNEAR: NearBalance = NearBalance::from_yoctonear(1); // 1 yoctoNEAR
```

**Comment by willemneal** [comment]
It's not that complicated and we can still do both.

**Comment by frol** [comment]
[near-gas](https://crates.io/crates/near-gas) and [near-token](https://crates.io/crates/near-token) crates were created to address this.
