### ISSUE TITLE
Consider using `u` for `µ`/micro

### ISSUE THREAD

**Issue by swfsql** [near/units-rs#5]
This doesn't seem to collide with other units' prefixes, and it would be easier to type.

**Comment by willemneal** [comment]
Good idea perhaps both?

Feel free to submit a PR; I no longer can approve PRs.

**Comment by frol** [comment]
@swfsql Please, use [near-gas](https://crates.io/crates/near-gas) and/or [near-token](https://crates.io/crates/near-token) crates instead of near-units. I am archiving this repo.
