### ISSUE TITLE
Repository is obsolete after near-sdk v4.0.0

### ISSUE THREAD

**Issue by sept-en** [near/units-rs#6]
After some constants for NEAR, Yocto, and TGas were added in https://github.com/near/near-sdk-rs/pull/640 (currently is a part of `near-sdk` v4.0.0 release), the functionality in this repo is no longer needed. As this repository seems not to be maintained, it could be archived.

**Comment by willemneal** [comment]
This also provides parsing string literals at compile time and can handle any unit not just the base units; so definitely not obsolete. I would maintain it as I wrote it, but I am no longer part of the near github org.

**Comment by frol** [comment]
@sept-en Please, use [near-gas](https://crates.io/crates/near-gas) and/or [near-token](https://crates.io/crates/near-token) crates instead of near-units. I will archive this repo.
