### ISSUE TITLE
Unmerged code - version discrepancy with crates.io 

### ISSUE THREAD

**Issue by sept-en** [near/units-rs#7]
@willemneal I noticed that [near-units-rs](https://crates.io/crates/near-units) crate on crates.io has version 0.2.0. Meantime, the source code in `master` in this repo is having `0.1.0`. I noticed that `fix/update-api` branch is [having](https://github.com/near/units-rs/blob/6ea4f0761d96926483503663cad24d01824fe68e/crates/units/Cargo.toml#L3) 0.2.0, but perhaps it was forgotten to be merged to `master`.

**Comment by willemneal** [comment]
@sept-en Just pushed #8
