### ISSUE TITLE
Volunteering to maintain this repo

### ISSUE THREAD

**Issue by ryancwalsh** [near/units-rs#9]
Hey @frol , 

This repo is great but could use some love. E.g. there are no docs, there are open issues and a PR, etc.

I'd be happy to maintain it.

Could I please be added as an admin of this repo? 

Or would it be better to transfer this repo to the NEARFoundation org here on GitHub (where I'm an admin)?

**Comment by frol** [comment]
@ryancwalsh Please, fork it for now, while we are still figuring out how to deal with this case

**Comment by frol** [comment]
@ryancwalsh Please, use [near-gas](https://crates.io/crates/near-gas) and/or [near-token](https://crates.io/crates/near-token) crates instead of near-units.
